### ISSUE TITLE
Decoder module available?

### ISSUE THREAD

**Issue by seanreed1111** [yeerwen/DeSD#3]
Hi, I see you sketched out the proper construction of the Decoder in your paper in section 2.4 and also in the readme (https://github.com/yeerwen/DeSD#fine-tune-desd-on-your-own-target-task). As I am not a researcher, was wondering if there are any recommendations on links  or some code you might be able to provide so I can reconstruct the Decoder class you used successfully? EDIT: I am asking because I definitely do not have enough GPUs to TFS. 
Thanks, Sean

**Comment by seanreed1111** [comment]
Ah, sorry, I have found my mistake. Thank you.

**Comment by yeerwen** [comment]
Hi, Sean
Sorry for my late reply, the details of the decoder we use have been introduced in Section 2.4. If you have any difficulties in implementing it, please let me know.
Best,
Yiwen

**Comment by seanreed1111** [comment]
Hi Yiwen,
Thank you for your email. I only asked for decoder module because I wanted
to experiment and see if your pretrained model could do a segmentation task
with only fine tuning of a few examples rather than also having enough
examples to train the decoder from scratch as well. I did notice your
commentary in section 2.4 and will train a decoder according to your
recommendations.

Thank you for your assistance! I look forward to diving in deeper to
understand your techniques.

Best Regards,

Sean
