### ISSUE TITLE
Decoder Implementation Details

### ISSUE THREAD

**Issue by LucaLumetti** [yeerwen/DeSD#5]
Hi, I was trying to implement the decoder you have used to perform the segmentation task but some doubts popped up in my mind regarding it. I've carefully read section 2.4 and noticed that you have inserted an ASPP module between the encoder and the decoder. The encoder, which is a ResNet50, would output a single vector with 2048 channels as it has a final AvgPooling layer, and to me it makes no sense to employ an ASPP module to a tensor with spatial shape $1 \times 1 \times 1$. My guess was that it must also be removed the final AvgPooling layer to employ the pre-trained model to perform a downstream task, this will make the model output a $1 \times 6 \times 6$ (given a $16 \times 96 \times 96$ input) and the ASPP block could have a meaningful reason to be placed here. Still, its receptive field would be quite limited by the small spatial resolution. Is there something I'm missing or that I've misunderstood?
If you could provide a detailed implementation of your decoder in the GitHub repository it would be really valuable! Thank you in advance!

Luca

**Comment by yeerwen** [comment]
Hi Luca,

We've integrated an ASPP module at the end of our encoder. This encoder is a modified version of ResNet50, from which we've removed the average pooling and fully connected layers. We have developed an end-to-end model that includes the encoder, an ASPP module, a decoder, and a segmentation head tailored for downstream segmentation tasks. Please note that for these downstream tasks, we've set the input size to 64x192x192.

Best,
Yiwen Ye

**Comment by LucaLumetti** [comment]
Thank you very much for the details, I'll try to implement your architecture from scratch. Still, it is unclear to me why the implementation of the final segmentation model, composed of the encoder, ASPP, and decoder, has been avoided from being uploaded in the source code. This makes other researchers struggle when trying to compare their method with yours, as well as probably missing out on some specific details not delineated in the paper.

Regards,
Luca Lumetti

**Comment by yeerwen** [comment]
Hi Luca,

Thank you for your insightful suggestion. Once our journal paper is accepted, we intend to open-source the code related to our downstream tasks, encompassing the model, training, and testing procedures. You can access it through the following link: https://github.com/yeerwen/CADS.

Best,
Yiwen Ye
